### ISSUE TITLE
Doesn't generate css and js files in cache dir

### ISSUE THREAD

**Issue by philippemiguet** [heristop/sf-combine-plugin#2] opened 2011-10-28 09:49 UTC
Hi, 

I’m using sfCombinePlugin and it works very well on my local machine. So I’ve tried to push it on our dev server, and here we have a little issue. 

It seems that the plugin is working because it generates the good “link” on the html header, but  doesn’t write the generated css et js files in the cache directory (chmod 777) 

Do you have any idea about this issue? 

I'm using symfony 1.4.4 on unix server, no APC on Apache

**Comment by kevindew** [comment] 2011-10-28 10:11
Hello, as the plugin uses the symfony caching system files will only be cached if this enabled in the symfony application.
Hope this helps.

**Comment by philippemiguet** [comment] 2011-10-28 13:09
Hello, not really. Even with "cache: true" in the cache.yml and settings.yml files, it doesn't change anything. And when I follow the css link generated by the plugin, I get an empty page.

**Comment by kevindew** [comment] 2011-10-28 15:18
Whether cache is on or off you should still get output so i imagine the issue is not related to the cache aspect and it's probably worth checking that an expection/fatal error isn't occuring somewhere?

**Comment by philippemiguet** [comment] 2011-10-28 15:54
Ok, good to know :) I thought the empty output were related to the cache, so I was focused on this! I've already checked symfony and Apache log, but nothing. I'll double check, and trace to see why I'm having an empty output! 

Thanks, I check this by next week, and post a solution or the origin of the problem ;)

**Comment by philippemiguet** [comment] 2011-11-07 15:48
So I've found where the issue comes from. 

In our web directory, we've done 3 sub-directories (one per app) each containing the css, js and images of each application. So, the path to our assets  for one app is /web/appname/css, for instance.

But the urls of each app point directly on their sub-folders, so the appname doesn't appear in the url. 
Then when the function "getAssetPath" from the "sfCombinerCss.class.php" is called, the generated path to the assets are incomplete. For instance, it generates /web/file.css instead of /web/appname/file.css.

It is because of the function used "_compute_public_path" which relies on the url to build the path to the assets.

I've made a temporary dirty fix by modifying a bit the function "getFilePath" in "sfCombineUtility.class.php". I've just added a new path in the "sfConfig::get('sf_web_dir') . '/appName' . $file".

All tips to fix it in a better way are welcome ;)

**Comment by kevindew** [comment] 2011-11-07 16:34
Hello, ah ok i see. Well the easy fix is when you call your assets use the absolute path e.g:

<?php use_javascript_grouped('/appName/js/my-js-file.js') ?>

I assume you're calling it relative, does symfony handle those assets ok without using sfCombine with the same path? as far as i was aware it goes through the same public path system that symfony uses.

**Comment by philippemiguet** [comment] 2011-11-07 17:11
Hi, we can't use this. We declare the js and css files in the view.yml files for each module (or action), not in the template itself. So we use include_combined_javascripts();

I'm not sure to understand what you mean in your last sentence... Can you explain me this in other terms?

I thought of another solution. The function "_compute_public_path" in AssetHelper.php uses "sfConfig::get('sf_web_css_dir_name', 'css')". But the properties "sf_web_css_dir_name" doesn't seem to exist (it always take the default argument "css"; i've tried to replace "css" by "foo" and it gave "foo"). 

EDIT: The solution which works for us, is to override/define this property in the setting.yml of the application e.g:

all:
  .settings:
    web_css_dir_name:   appName/css

**Comment by kevindew** [comment] 2011-11-08 17:02
Hello, yeah i just meant that if sfCombine wasn't installed did the assets work correctly (to try identify if there is an inconsistency between how we generate asset paths in sfCombine and how symfony does by default).

Glad you've got it working there, i assume you can also just put absolute path in your view.yml.

**Comment by Jeff-Mott-OR** [comment] 2011-12-11 08:46
I experienced a similar issue. I think the problem is that sfCombine uses the public web path as part of the file system path. But the URL path could be arbitrary and have nothing to do with the system path.

In sfCombineCombiner, in _collateFileContents, you do:

```
  $assetPath = $this->getAssetPath($file);

  // break off any query string in the name
  $fileParts = explode('?', $assetPath);
  $fileName = $fileParts[0];
  ...
    $filePath = sfCombineUtility::getFilePath($fileName);
```

And getFilePath, in turn, will try to prepend the web dir.

```
  sfConfig::get('sf_web_dir') . $file,
```

And what happens is Combine tries looking for the file in:

```
  /system/path/to/web/then/url/path/which/could/be/anything/css/file.css
```

I've so far been able to get around this by trimming off the relative URL root when getting the file path:

  static public function getFilePath($file)
  {
    // trim relative
    $request = sfContext::getInstance()->getRequest();
    $relativeUrlRoot = $request->getRelativeUrlRoot();
    $file = str_replace($relativeUrlRoot, '', $file);
    ...

**Comment by Jeff-Mott-OR** [comment] 2011-12-11 08:51
...but that was a quick hack. I think the better solution would be to not mix URL paths and system paths in the first place.

**Comment by Jeff-Mott-OR** [comment] 2011-12-11 13:17
P.S. Still loving the plugin. Keep up the great work. :-)

**Comment by kevindew** [comment] 2011-12-11 17:23
Thanks Jeff, If i recall correctly it's intentional to be relative to public path so it can fallback in dev environments to the standard path. So (assuming I've understood you correctly) might just be a case that it's going a bit out of scope for this project.

**Closed as completed** 2017-10-05 11:56 UTC
